version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
    ports:
        - "5432:5432"
    networks:
      - my-net

  app:
    image: my-app
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jira
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-net

networks:
  my-net: