version: "3.9"

services:
  db:
    container_name: jira-postgres-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    container_name: jira
    image: my-app
    build: .
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jira
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
#    depends_on:
#      - db

  nginx:
    container_name: nginx-jira
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - nginx_config_jira:/etc/nginx/conf.d
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./resources:/opt/jirarush/resources:ro
    networks:
      - frontend
    depends_on:
      - app

networks:
  backend:
  frontend:

volumes:
  nginx_config_jira:
  postgresql_data: