# template for server
app:
  host-url: http://localhost
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:2345/jira}
    username: ${DB_USERNAME:jira}
    password: ${DB_PASSWORD:JiraRush}

